version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
      - ./app/static:/app/app/static
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - cats_images:/usr/share/nginx/html/static/CatsImages
      - user_uploads:/usr/share/nginx/html/static/uploads
    depends_on:
      - web
    restart: unless-stopped

volumes:
  cats_images:
  user_uploads:
  db_volume:

