version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
      # Монтируем статику, чтобы изменения сразу применялись
      - ./app/static:/app/app/static
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./app/static:/usr/share/nginx/html/static
    depends_on:
      - web
    restart: unless-stopped